# Generated by Django 3.0.4 on 2020-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteText', models.CharField(max_length=500)),
                ('quoteAuthor', models.CharField(max_length=30)),
            ],
        ),
    ]
