--
-- 由SQLiteStudio v3.2.1 产生的文件 周六 3月 28 19:38:44 2020
--
-- 文本编码：System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- 表：quotes
CREATE TABLE quotes (id INTEGER PRIMARY KEY AUTOINCREMENT, quoteText VARCHAR (500), quoteAuthor VARCHAR (30));
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (1, 'The least movement is of importance to all nature. The entire ocean is affected by a pebble.', 'Blaise Pascal');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (2, 'As you think, so shall you become.', 'Bruce Lee');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (3, 'In every adversity there lies the seed of an equivalent advantage. In every defeat is a lesson showing you how to win the victory next time. ', 'Robert Collier');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (4, 'I would rather be attacked than unnoticed. For the worst thing you can do to an author is to be silent as to his works. An assault upon a town is a bad thing; but starving it is still worse. ', 'Samuel Johnson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (5, 'We have a hunger of the mind which asks for knowledge of all around us, and the more we gain, the more is our desire; the more we see, the more we are capable of seeing. ', 'Maria Mitchell');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (9, 'The doors we open and close each day decide the lives we live.', 'Flora Whittemore');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (11, 'Knowing is not enough; we must apply! ', 'Johann Wolfgang von Goethe');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (15, 'You can do it if you believe you can!  ', 'Napoleon Hill ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (22, 'A time splashed with interest, wounded with tragedy, crevassed with joy — that’s the time that seems long in the memory. And this is right when you think about it. Eventlessness has no posts to drape duration on.', 'John Steinbeck');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (25, 'Time you enjoy wasting, was not wasted.  ', 'John Lennon ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (26, 'Someone is special only if you tell them.  ', 'Byron Pulsifer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (27, 'Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending. ', '');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (28, 'Smile, breathe and go slowly. ', 'Thich Nhat Hanh');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (29, 'Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.', 'Douglas Adams');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (30, 'All know the way; few actually walk it. ', 'Bodhidharma');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (31, 'The only real valuable thing is intuition.  ', 'Albert Einstein');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (32, 'There are basically two types of people. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded. ', 'Mark Twain');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (33, 'Our greatest glory is not in never failing but rising everytime we fall.', '');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (34, 'A goal without a plan is just a wish. ', 'Larry Elder ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (36, 'We are the leaves of one branch, the drops of one sea, the flowers of one garden. ', 'Jean Lacordaire');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (37, 'I care not so much what I am to others as what I am to myself. I will be rich by myself, and not by borrowing. ', 'Michel de Montaigne');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (38, 'Our lives are the only meaningful expression of what we believe and in Whom we believe. And the only real wealth, for any of us, lies in our faith. ', 'Gordon  Hinckley ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (39, 'Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom. ', 'Marcel Proust');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (40, 'Wherever you go, go with all your heart.  ', 'Confucius ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (41, 'The two most powerful warriors are patience and time.  ', 'Leo Tolstoy ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (42, 'There are no limitations to the mind except those we acknowledge.  ', 'Napoleon Hill ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (43, 'Error is discipline through which we advance. ', 'Channing');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (44, 'The more you know yourself, the more you forgive yourself. ', 'Confucius');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (45, 'If we could see the miracle of a single flower clearly, our whole life would change. ', 'Buddha');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (46, 'Life is a progress, and not a station. ', 'Ralph Emerson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (47, 'Reality leaves a lot to the imagination. ', 'John Lennon');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (48, 'Imagination rules the world.  ', 'Napoleon Bonaparte ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (49, 'It does not matter how slowly you go as long as you do not stop. ', 'Confucius ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (50, 'Where all think alike, no one thinks very much. ', 'Walter Lippmann');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (51, 'Obstacles are those things you see when you take your eyes off the goal. ', 'Hannah More');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (52, 'Nobody made a greater mistake than he who did nothing because he could do only a little. ', 'Edmund Burke');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (53, 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. ', 'Albert Schweitzer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (54, 'Without passion man is a mere latent force and possibility, like the flint which awaits the shock of the iron before it can give forth its spark.  ', 'Amiel');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (55, 'The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live. ', 'Mortimer Adler');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (56, 'The key to transforming our hearts and minds is to have an understanding of how our thoughts and emotions work.', 'Dalai Lama');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (57, 'It is only when the mind and character slumber that the dress can be seen. ', 'Ralph Waldo Emerson ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (58, 'If one advances confidently in the direction of his dream, and endeavours to live the life which he had imagines, he will meet with a success unexpected in common hours.', 'Henry David Thoreau');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (59, 'Consider that not only do negative thoughts and emotions destroy our experience of peace, they also undermine our health.', 'Dalai Lama');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (60, 'Everything you are against weakens you. Everything you are for empowers you.  ', 'Wayne Dyer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (61, 'Time is the wisest counsellor of all. ', 'Pericles');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (62, 'Your task is not to seek love, but merely to seek and find all the barriers within yourself that you have built against it.', 'Rumi');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (63, 'What is a weed? A plant whose virtues have not yet been discovered. ', 'Ralph Emerson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (64, 'It is not enough to have a good mind; the main thing is to use it well.  ', 'Rene Descartes ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (65, 'Whoever is happy will make others happy, too. ', 'Mark Twain');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (66, 'Without some goals and some efforts to reach it, no man can live. ', 'John Dewey');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (67, 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (68, 'Do, or do not. There is no try. ', 'Yoda');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (69, 'There surely is in human nature an inherent propensity to extract all the good out of all the evil. ', 'Benjamin Haydon');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (70, 'Snowflakes are one of natures most fragile things, but just look what they can do when they stick together. ', 'Vista Kelly ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (71, 'Gratitude is riches. Complaint is poverty. ', 'Doris Day');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (72, 'Be not angry that you cannot make others as you wish them to be, since you cannot make yourself as you wish to be. ', 'Thomas Kempis');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (73, 'Think how hard physics would be if particles could think.', 'Murray Gell-Mann');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (74, 'You can complain because roses have thorns, or you can rejoice because thorns have roses. ', ' Ziggy');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (75, 'We should all be thankful for those people who rekindle the inner spirit. ', 'Albert Schweitzer ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (76, 'Silence is deep as Eternity, Speech is shallow as Time. ', 'Carlyle');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (77, 'Wisdom is the supreme part of happiness. ', 'Sophocles');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (78, 'As an organizer I start from where the world is, as it is, not as I would like it to be. ', 'Saul Alinsky');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (79, 'The key to growth is the introduction of higher dimensions of consciousness into our awareness.  ', 'Lao Tzu ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (80, 'Try not to become a man of success, but rather try to become a man of value.', 'Albert Einstein');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (83, 'We lost because we told ourselves we lost.  ', 'Leo Tolstoy ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (86, 'One who gains strength by overcoming obstacles possesses the only strength which can overcome adversity.  ', 'Albert Schweitzer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (90, 'The wisest men follow their own direction. ', 'Euripides');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (91, 'We are Divine enough to ask and we are important enough to receive.  ', 'Wayne Dyer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (92, 'You are always free to change your mind and choose a different future, or a different past.  ', 'Richard Bach ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (93, 'To know oneself is to study oneself in action with another person.  ', 'Bruce Lee ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (94, 'My reputation grows with every failure. ', 'George Shaw');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (95, 'You cannot have what you do not want.', 'John Acosta');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (97, 'The day is already blessed, find peace within it.', '');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (98, 'Well done is better than well said.  ', 'Benjamin Franklin');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (99, 'People are so constituted that everybody would rather undertake what they see others do, whether they have an aptitude for it or not. ', 'Johann Wolfgang Von Goethe ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (100, 'Intuition will tell the thinking mind where to look next. ', 'Jonas Salk');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (102, 'Blaze with the fire that is never extinguished. ', 'Luisa Sigea');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (103, 'If the stars should appear but one night every thousand years how man would marvel and adore. ', 'Ralph Emerson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (104, 'It is impossible for a man to learn what he thinks he already knows. ', 'Epictetus');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (105, 'Moral excellence comes about as a result of habit. We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts. ', 'Aristotle');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (106, 'How far that little candle throws its beams! So shines a good deed in a naughty world.', 'William Shakespeare');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (107, 'Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.  ', 'Lao Tzu');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (108, 'Silence is the true friend that never betrays. ', 'Confucius');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (109, 'I am glad that I paid so little attention to good advice; had I abided by it I might have been saved from some of my most valuable mistakes. ', 'Edna Millay');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (110, 'I am not afraid of tomorrow, for I have seen yesterday and I love today. ', 'William White');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (111, 'An optimist is a person who sees a green light everywhere, while the pessimist sees only the red spotlight... The truly wise person is colour-blind.', 'Albert Schweitzer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (112, 'I am always doing that which I can not do, in order that I may learn how to do it. ', 'Pablo Picasso');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (113, 'Develop an attitude of gratitude, and give thanks for everything that happens to you, knowing that every step forward is a step toward achieving something bigger and better than your current situation.  ', 'Brian Tracy ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (114, 'Imagination is the living power and prime agent of all human perception. ', 'Samuel Taylor Coleridge');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (115, 'A man may fulfil the object of his existence by asking a question he cannot answer, and attempting a task he cannot achieve.', 'Oliver Wendell Holmes');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (116, 'The awareness of our own strength makes us modest.', 'Paul Cezanne');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (117, 'Well begun is half done.  ', 'Aristotle ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (118, 'Everything has beauty, but not everyone sees it.  ', 'Confucius ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (119, 'If we are facing in the right direction, all we have to do is keep on walking.', '');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (120, 'Focusing your life solely on making a buck shows a poverty of ambition. It asks too little of yourself. And it will leave you unfulfilled. ', 'Barack Obama');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (121, 'There are people who have money and people who are rich. ', 'Coco Channel');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (122, 'Kindness is the golden chain by which society is bound together. ', 'Johann Wolfgang von Goethe');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (123, 'One secret of success in life is for a man to be ready for his opportunity when it comes. ', 'Benjamin Disraeli ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (124, 'Adversity has the effect of eliciting talents, which in prosperous circumstances would have lain dormant. ', 'Horace');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (125, 'Friendship with oneself is all important because without it one cannot be friends with anybody else in the world. ', 'Eleanor Roosevelt');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (126, 'The best teacher is experience learned from failures. ', 'Byron Pulsifer ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (127, 'Never apologize for showing feeling. When you do so, you apologize for truth.', 'Benjamin Disraeli');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (128, 'I always wanted to be somebody, but I should have been more specific.', 'Lily Tomlin');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (129, 'It is never too late. Even if you are going to die tomorrow, keep yourself straight and clear and be a happy human being today.', 'Lama Yeshe');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (130, 'Everyone should carefully observe which way his heart draws him, and then choose that way with all his strength. ', 'Hasidic saying');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (131, 'The belief that youth is the happiest time of life is founded upon a fallacy. The happiest person is the person who thinks the most interesting thoughts, and we grow happier as we grow older. ', 'William Phelps');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (132, 'Things turn out best for those who make the best of the way things turn out. ', 'Jack Buck ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (133, 'Imagination will often carry us to worlds that never were. But without it we go nowhere. ', 'Carl Sagan');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (134, 'Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared. ', 'Buddha');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (135, 'The odds of hitting your target go up dramatically when you aim at it. ', 'Mal Pancoast ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (136, 'Perseverance is a great element of success. If you only knock long enough and loud enough at the gate, you are sure to wake up somebody.  ', 'Henry Longfellow ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (137, 'Obstacles are those frightful things you see when you take your eyes off your goal. ', 'Henry Ford');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (138, 'Dreams come true. Without that possibility, nature would not incite us to have them. ', 'John Updike');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (139, 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe. ', 'Abraham Lincoln');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (140, 'If one advances confidently in the direction of his dream, and endeavours to live the life which he had imagines, he will meet with a success unexpected in common hours.', 'Henry David Thoreau');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (141, 'The undertaking of a new action brings new strength. ', 'Richard Evans ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (142, 'Love and kindness are never wasted. They always make a difference. They bless the one who receives them, and they bless you, the giver. ', 'Barbara De Angelis');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (143, 'Peace of mind is not the absence of conflict from life, but the ability to cope with it.', 'Unknown');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (144, 'You, yourself, as much as anybody in the entire universe, deserve your love and affection.  ', 'Buddha');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (145, 'I walk slowly, but I never walk backward.  ', 'Abraham Lincoln');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (146, 'The most important point is to accept yourself and stand on your two feet.', 'Shunryu Suzuki');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (147, 'Edison failed 10,000 times before he made the electric light. Do not be discouraged if you fail a few times.', 'Napoleon Hill');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (149, 'No garden is without its weeds. ', 'Thomas Fuller');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (150, 'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. ', 'Marcus Aurelius ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (152, 'Love and kindness are never wasted. They always make a difference. They bless the one who receives them, and they bless you, the giver. ', 'Barbara De Angelis');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (153, 'Truth, and goodness, and beauty are but different faces of the same all. ', 'Ralph Emerson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (154, 'Be what you are. This is the first step toward becoming better than you are.', 'Julius Charles Hare');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (155, 'When I let go of what I am, I become what I might be.', 'Lao Tzu');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (156, 'No one who achieves success does so without the help of others. The wise and confident acknowledge this help with gratitude. ', 'Alfred North Whitehead');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (157, 'Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more.  ', 'Nikola Tesla ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (158, 'Our deepest wishes are whispers of our authentic selves. We must learn to respect them. We must learn to listen. ', 'Sarah Breathnach');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (159, 'You are the only person on earth who can use your ability. ', 'Zig Ziglar ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (160, 'Fame usually comes to those who are thinking about something else. ', 'Holmes');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (161, 'Your vision will become clear only when you look into your heart. Who looks outside, dreams. Who looks inside, awakens. ', 'Carl Jung');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (162, 'Friends are those rare people who ask how we are and then wait to hear the answer. ', 'Ed Cunningham ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (163, 'A short saying oft contains much wisdom. ', 'Sophocles');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (164, 'We lost because we told ourselves we lost.  ', 'Leo Tolstoy ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (165, 'Everything has beauty, but not everyone sees it.  ', 'Confucius ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (166, 'I am like a falling star who has finally found her place next to another in a lovely constellation, where we will sparkle in the heavens forever. ', 'Amy Tan');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (167, 'You may be deceived if you trust too much, but you will live in torment unless you trust enough. ', ' Frank Crane');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (168, 'Happiness is a Swedish sunset — it is there for all, but most of us look the other way and lose it. ', 'Mark Twain');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (169, 'To be aware of a single shortcoming in oneself is more useful than to be aware of a thousand in someone else. ', 'Tenzin Gyatso, 14th Dalai Lama');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (170, 'We cannot do everything at once, but we can do something at once.  ', 'Calvin Coolidge ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (171, 'Happiness cannot be travelled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace and gratitude.', 'Denis Waitley');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (172, 'If it is not right do not do it; if it is not true do not say it. ', 'Marcus Aurelius');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (173, 'I would rather be attacked than unnoticed. For the worst thing you can do to an author is to be silent as to his works. An assault upon a town is a bad thing; but starving it is still worse. ', 'Samuel Johnson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (174, 'There are two ways to slide easily through life: to believe everything or to doubt everything; both ways save us from thinking. ', 'Alfred Korzybski');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (175, 'No alibi will save you from accepting the responsibility. ', 'Napoleon Hill');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (176, 'Be the chief but never the lord.  ', 'Lao Tzu ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (177, 'There is no failure except in no longer trying. ', 'Elbert Hubbard');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (178, 'Since you alone are responsible for your thoughts, only you can change them.', 'Paramahansa Yogananda');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (179, 'Beauty is all around us amidst strife and turmoil to be seen by those who look not to those who wish. ', 'Byron Pulsifer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (180, 'Everyone has been made for some particular work, and the desire for that work has been put in every heart.  ', 'Rumi ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (181, 'Never apologize for showing feeling. When you do so, you apologize for truth.', 'Benjamin Disraeli');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (182, 'Blessed is the man who expects nothing, for he shall never be disappointed. ', 'Alexander Pope');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (183, 'You get peace of mind not by thinking about it or imagining it, but by quietening and relaxing the restless mind.', 'Remez Sasson');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (184, 'There is no way to happiness, happiness is the way.', 'Thich Nhat Hanh');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (185, 'Meditation brings wisdom; lack of mediation leaves ignorance. Know well what leads you forward and what hold you back, and choose the path that leads to wisdom. ', 'Buddha');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (186, 'If you want your life to be more rewarding, you have to change the way you think.  ', 'Oprah Winfrey ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (187, 'Transformation does not start with some one else changing you; transformation is an inner self reworking of what you are now to what you will be. ', ' Byron Pulsifer');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (188, 'If you find yourself in a hole, the first thing to do is stop digging. ', 'Will Rogers ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (189, 'Remember that sometimes not getting what you want is a wonderful stroke of luck.', 'Dalai Lama');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (190, 'Do good by stealth, and blush to find it fame. ', 'Alexander Pope');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (191, 'All action results from thought, so it is thoughts that matter.  ', 'Sai Baba ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (192, 'He who does not trust enough, Will not be trusted.  ', 'Lao Tzu ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (193, 'It is better to have enough ideas for some of them to be wrong, than to be always right by having no ideas at all. ', 'Edward de Bono');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (194, 'In the end we retain from our studies only that which we practically apply. ', 'Johann Wolfgang von Goethe ');
INSERT INTO quotes (id, quoteText, quoteAuthor) VALUES (195, 'Beware of the half truth. You may have gotten hold of the wrong half.', 'Unknown');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
